Issue 105: Add support for sa_key_provision_ta()
rdkcentral/tasecureapi pull request #109
Opened 2024-02-13 17:35 UTC by riwoh

2024-02-23 17:58 UTC, hchoi-brcm commented on reference/src/client/include/sa_key.h
> +} sa_ta_key_type;
Other types and enumeration definitions are in sa_types.h and sa_key.h contains function declarations for key module. Could we keep this concept for TA key provision?

2024-02-27 05:58 UTC, mhabrat requested changes

2024-02-27 05:58 UTC, mhabrat commented on reference/src/clientimpl/src/sa_key_provision.c
> +         break;
We should report that the key provisioning type is unknown if we get here.

2024-02-27 05:58 UTC, mhabrat commented on reference/src/client/include/sa_key.h
> +  NETFLIX_PROVISIONING
Include support for Apple provisioning.

2024-02-27 05:58 UTC, mhabrat commented on reference/src/clientimpl/src/sa_key_provision.c
> +   switch(ta_key_type) {
Add support for Apple provisioning.

2024-02-27 05:58 UTC, mhabrat commented on reference/src/clientimpl/src/sa_key_provision.c
> +               ERROR("OOM");
Please adopt standard secapi3 error reporting.

2024-02-27 05:58 UTC, mhabrat commented on reference/src/clientimpl/src/sa_key_provision.c
> +            /*here just provide an examlpe to pass certification data,
Let's inlcude the "TODO SoC Vendor" label everywhere the SoC vendor is expected to make changes.

2024-02-27 05:58 UTC, mhabrat commented on reference/src/clientimpl/src/sa_key_provision.c
> +                        wvProvision->oemDevicePrivateKeyLength,NULL);
Shouldn't the parameters field provide the SA_KEY_FORMAT_SOC type to denote the key is protected with the SOC key?

2024-02-27 05:58 UTC, mhabrat commented on reference/src/clientimpl/src/sa_key_provision.c
> +            if(0 == (memcmp(prProvision->privateKey, "SIGN", 4))) {
The SIGN attribute is specific to Widevine only.

2024-02-27 05:58 UTC, mhabrat commented on reference/src/clientimpl/src/sa_key_provision.c
> +            status = sa_key_import(rsa_key, SA_KEY_FORMAT_EXPORTED,
Shouldn't the parameters field provide the SA_KEY_FORMAT_SOC type to denote the key is protected with the SOC key?

2024-02-27 05:58 UTC, mhabrat commented on reference/src/clientimpl/src/sa_key_provision.c
> +            INFO("wraaping length: %d", ((NetflixProvisioning*)(in))->wrappingKeyLength);
```suggestion
            INFO("wraping length: %d", ((NetflixProvisioning*)(in))->wrappingKeyLength);
```

2024-02-27 05:58 UTC, mhabrat commented on reference/src/clientimpl/src/sa_key_provision.c
> +                                  NULL);
Shouldn't the parameters field provide the SA_KEY_FORMAT_SOC type to denote the key is protected with the SOC key?

2024-02-27 05:58 UTC, mhabrat commented on reference/src/clientimpl/src/sa_key_provision.c
> +            sa_status status_wrapping = sa_key_import(sa_wrapping_key, SA_KEY_FORMAT_EXPORTED,
Shouldn't the parameters field provide the SA_KEY_FORMAT_SOC type to denote the key is protected with the SOC key?

2024-02-27 05:58 UTC, mhabrat commented on reference/src/client/test/sa_key_provision.cpp
> +#define wievine_oem_privatekey "/opt/drm/0351000003510001.key"
Let's not leak Comcast specific information via open source implementations.

2024-02-27 05:58 UTC, mhabrat commented on reference/src/client/test/sa_key_provision.cpp
> + /*there are two file 0351000003510001.key and 0651000006510001.bin under
Let's not leak Comcast specific implementations through open source implementations.

2024-05-06 14:58 UTC, mhabrat requested changes

2024-05-06 14:58 UTC, mhabrat commented on reference/src/client/include/sa_key.h
> +    Vendor TA Key updates will only be written to TAs supporting secure store upon receiving a new
Indentation.

2024-05-06 14:58 UTC, mhabrat commented on reference/src/client/include/sa_key.h
> +    [TA Key Type Definition](#ta-key-type-definition).
```suggestion
   [TA Key Type Definition](#ta-key-type-definition).
```

2024-05-06 14:58 UTC, mhabrat commented on reference/src/client/include/sa_types.h
> +}PLAYREADY_MODEL_TYPE;
```suggestion
} PLAYREADY_MODEL_TYPE;
```

2024-05-06 14:58 UTC, mhabrat commented on reference/src/client/test/sa_crypto_cipher_process_rsa_pkcs1v15.cpp
> +
Remove excess blank space.

2024-05-06 14:58 UTC, mhabrat commented on reference/test/SecApiKeyProvisionTaTests.md
> +
Remove excess blank lines at endo of file.

2024-05-06 17:07 UTC, mhabrat approved these changes

2024-05-08 06:43 UTC, merged