Issue 7: Standardize all private keys to OneAssymetricKey format and public keys to SubjectPublicKeyInfo format
rdkcentral/tasecureapi pull request #14
Opened 2022-06-19 22:41 UTC by ericeberry

2022-06-20 19:09 UTC, mhabrat requested changes

2022-06-20 21:15 UTC, ericeberry commented on reference/src/taimpl/src/internal/typej.c
> + * Copyright 2019-2022 Comcast Cable Communications Management, LLC
I forgot to change it when I completed Issue 3.

2022-06-20 21:16 UTC, ericeberry commented on reference/src/client/src/sa_engine_pkey.c
> +                ERROR("EVP_PKEY_get_octet_string_param failed");
Done

2022-06-20 21:17 UTC, ericeberry commented on reference/src/client/test/sa_engine_pkey_decrypt.cpp
> +                GTEST_FATAL_FAILURE_("EVP_PKEY_CTX_ctrl failed");
Done

2022-06-20 21:18 UTC, ericeberry commented on reference/src/client/test/sa_engine_pkey_decrypt.cpp
> +                GTEST_FATAL_FAILURE_("EVP_PKEY_CTX_ctrl failed");
Done

2022-06-21 04:43 UTC, mhabrat approved these changes

2022-06-21 17:31 UTC, merged