Issue 54: Add support for SA_KDF_ALGORITHM_COMMON_ROOT_KEY_LADDER
rdkcentral/tasecureapi pull request #55
Opened 2023-03-02 00:11 UTC by ericeberry

2023-03-29 23:02 UTC, riwoh approved these changes

2023-03-30 05:49 UTC, ericeberry commented on reference/src/client/test/sa_key_common.cpp
> +    return status;
Done

2023-03-31 22:51 UTC, mhabrat requested changes
Can we move the root_keystore.p12 to a resource directory within the test folder?

2023-03-31 22:51 UTC, mhabrat commented on reference/src/client/test/sa_key_common.cpp
> +        char name[16];
Use enums for constant sizes.

2023-03-31 22:53 UTC, ericeberry commented on reference/src/client/test/sa_key_common.cpp
> +        char name[16];
This is fixed in another PR.

2023-03-31 23:38 UTC, ericeberry commented
keystore moved.

2023-04-02 23:14 UTC, mhabrat approved these changes

2023-04-03 05:04 UTC, mhabrat approved these changes

2023-04-03 05:04 UTC, merged