RFC 0000-integer_overflow_systematic_checks
rdkcentral/tasecureapi pull request #64
Opened 2023-04-07 21:11 UTC by bsimondi

2023-04-12 22:16 UTC, ericeberry requested changes
Please change directory to 0005-integer_overflow_systematic_checks.

Also please limit line length to 100 characters.

2023-04-28 00:30 UTC, kihun-amlogic approved these changes

2023-04-28 01:52 UTC, LisShen approved these changes

2023-04-28 02:38 UTC, hchoi-brcm submitted a review, later dismissed

2023-05-02 22:14 UTC, ericeberry submitted a review, later dismissed

2023-05-06 04:07 UTC, mhabrat requested changes

2023-05-06 04:07 UTC, mhabrat commented on docs/rfcs/accepted/0005-integer_overflow_systematic_checks/README.md
> +https://gcc.gnu.org/onlinedocs/gcc/Integer-Overflow-Builtins.html
```suggestion
[GCC Integer Overflow Builtins](https://gcc.gnu.org/onlinedocs/gcc/Integer-Overflow-Builtins.html)
```

2023-05-06 04:07 UTC, mhabrat commented on docs/rfcs/accepted/0005-integer_overflow_systematic_checks/README.md
> +https://github.com/OP-TEE/optee_os/blob/master/lib/libutils/ext/include/util.h
```suggestion
[OP-TEE Overflow Macros](https://github.com/OP-TEE/optee_os/blob/master/lib/libutils/ext/include/util.h).
```

2023-05-06 04:07 UTC, mhabrat commented on docs/rfcs/accepted/0005-integer_overflow_systematic_checks/README.md
> +-
```suggestion
- [Integer Overflow or Wraparound](https://cwe.mitre.org/data/definitions/190.html).
```

2023-05-06 04:07 UTC, mhabrat commented on docs/rfcs/accepted/0005-integer_overflow_systematic_checks/README.md
> +-
```suggestion
- None.

```

2023-05-06 04:07 UTC, mhabrat commented on docs/rfcs/accepted/0005-integer_overflow_systematic_checks/README.md
> +field/parameter that can be under the influence of the outside world. add (A+B), sub (A-B), and mult
```suggestion
field/parameter that can be under the influence of the outside world. add (A+B), subtract (A-B), and multiply
```

2023-05-06 04:09 UTC, mhabrat requested changes
Minor nits corrected and references added.

2023-05-10 20:39 UTC, ericeberry commented on docs/rfcs/accepted/0005-integer_overflow_systematic_checks/README.md
> +-
Done

2023-05-10 20:39 UTC, ericeberry commented on docs/rfcs/accepted/0005-integer_overflow_systematic_checks/README.md
> +-
Done

2023-05-10 20:39 UTC, ericeberry commented on docs/rfcs/accepted/0005-integer_overflow_systematic_checks/README.md
> +values, e.g. (A+B+C+B) should be decomposed on
Done

2023-05-10 20:39 UTC, ericeberry commented on docs/rfcs/accepted/0005-integer_overflow_systematic_checks/README.md
> +- check independently A, B, C and D values
Done

2023-05-10 20:40 UTC, ericeberry approved these changes

2023-05-10 22:24 UTC, ericeberry approved these changes

2023-05-14 17:04 UTC, mhabrat approved these changes

2023-05-14 18:07 UTC, merged