RFC 0000-ree_tee_boundary_simplification_and_hardening
rdkcentral/tasecureapi pull request #67
Opened 2023-04-07 23:19 UTC by bsimondi

2023-04-28 00:31 UTC, kihun-amlogic approved these changes

2023-04-28 01:53 UTC, LisShen approved these changes

2023-04-28 02:39 UTC, hchoi-brcm approved these changes

2023-05-02 22:18 UTC, ericeberry submitted a review, later dismissed

2023-05-06 05:18 UTC, mhabrat requested changes

2023-05-06 05:18 UTC, mhabrat commented on docs/rfcs/accepted/0008-ree_tee_boundary_simplification_and_hardening/README.md
> +Crossing trust boundaries create opportunities for adversarial code running in less trusted
```suggestion
Crossing trust boundaries creates opportunities for adversarial code running in a less trusted 
```

2023-05-06 05:18 UTC, mhabrat commented on docs/rfcs/accepted/0008-ree_tee_boundary_simplification_and_hardening/README.md
> +environment, to attack the more trusted environment. Integrating a 3rd party code on the more
```suggestion
environment to attack the more trusted environment. Integrating third party code within the  
```

2023-05-06 05:18 UTC, mhabrat commented on docs/rfcs/accepted/0008-ree_tee_boundary_simplification_and_hardening/README.md
> +trusted world, is error prone and innevitably creates security loopholes proportionally linear
```suggestion
trusted environment is error prone and inevitably creates security loopholes proportionally linear 
```

2023-05-06 05:18 UTC, mhabrat commented on docs/rfcs/accepted/0008-ree_tee_boundary_simplification_and_hardening/README.md
> +with the complexity of the integration. Special attention should be made to move the complexity
```suggestion
to the complexity of the integration. Special attention should be made to move the complexity 
```

2023-05-06 05:18 UTC, mhabrat commented on docs/rfcs/accepted/0008-ree_tee_boundary_simplification_and_hardening/README.md
> +Trusted Application (TA), executing in a Trusted Execution Environment (TEE), and that a client
```suggestion
Trusted Application (TA), executing in a Trusted Execution Environment (TEE), and that client 
```

2023-05-06 05:18 UTC, mhabrat commented on docs/rfcs/accepted/0008-ree_tee_boundary_simplification_and_hardening/README.md
> +TA, to compromise secrets, gain execution etc. Every single parameter of all of the exposed APIs,
```suggestion
TA, to compromise secrets, gain execution control, etc. Every single parameter of all of the exposed APIs, 
```

2023-05-06 05:18 UTC, mhabrat commented on docs/rfcs/accepted/0008-ree_tee_boundary_simplification_and_hardening/README.md
> +shall be consider under an attacker control, and properly sanitized.
```suggestion
shall be considered under an attacker's control, and properly sanitized.
```

2023-05-06 05:18 UTC, mhabrat commented on docs/rfcs/accepted/0008-ree_tee_boundary_simplification_and_hardening/README.md
> +-
Add None to all empty sections.

2023-05-06 05:18 UTC, mhabrat commented on docs/rfcs/accepted/0008-ree_tee_boundary_simplification_and_hardening/README.md
> +-
All?

2023-05-06 05:18 UTC, mhabrat commented on docs/rfcs/accepted/0008-ree_tee_boundary_simplification_and_hardening/README.md
> +Implementing a systematic sanitization layer for all APIs exposed by TASECUREAPI allows to isolate
```suggestion
Implementing a systematic sanitization layer for all APIs exposed by TASECUREAPI allows isolation 
```

2023-05-06 05:18 UTC, mhabrat commented on docs/rfcs/accepted/0008-ree_tee_boundary_simplification_and_hardening/README.md
> +and seal the inner code logic against partners integration shortcomings or mistakes that would not
```suggestion
and seals the inner code logic against partners' integration shortcomings or mistakes that would not 
```

2023-05-06 05:18 UTC, mhabrat commented on docs/rfcs/accepted/0008-ree_tee_boundary_simplification_and_hardening/README.md
> +how secure is the integration toward deterministic sanitization checks handled in the inner code
```suggestion
how secure the integration is toward deterministic sanitization checks handled in the inner code 
```

2023-05-06 05:18 UTC, mhabrat commented on docs/rfcs/accepted/0008-ree_tee_boundary_simplification_and_hardening/README.md
> +This becomes particularly relevant as the number of partners integrating the code grow. Reducing
```suggestion
This becomes particularly relevant as the number of partners integrating the code grows. Reducing 
```

2023-05-06 05:18 UTC, mhabrat commented on docs/rfcs/accepted/0008-ree_tee_boundary_simplification_and_hardening/README.md
> +the complexity on partners hands, also reduce the complexity of the code review when verifying
```suggestion
the complexity on partners hands, also reduces the complexity of the code review when verifying 
```

2023-05-06 05:18 UTC, mhabrat commented on docs/rfcs/accepted/0008-ree_tee_boundary_simplification_and_hardening/README.md
> +-
```suggestion
- None.

```

2023-05-06 05:18 UTC, mhabrat commented on docs/rfcs/accepted/0008-ree_tee_boundary_simplification_and_hardening/README.md
> +All parameters getting in the SEC API lib can be tricked and have malicious values. Said
```suggestion
All parameters passed to the TASECUREAPI lib can be tricked and have malicious values. Said 
```

2023-05-06 05:18 UTC, mhabrat commented on docs/rfcs/accepted/0008-ree_tee_boundary_simplification_and_hardening/README.md
> +code, shall be sanitized before being used. For all APIs. No exceptions.
```suggestion
TASECUREAPI code, shall be sanitized before being used. For all APIs. No exceptions.
```

2023-05-06 05:18 UTC, mhabrat commented on docs/rfcs/accepted/0008-ree_tee_boundary_simplification_and_hardening/README.md
> +offer a compatible or easy to wire interface.
```suggestion
offer a compatible or easy to wire interface for this architecture.
```

2023-05-06 05:18 UTC, mhabrat commented on docs/rfcs/accepted/0008-ree_tee_boundary_simplification_and_hardening/README.md
> +Direct use of GP APIs (or providing an optional glue for GP) would allow the inner code also to
```suggestion
Direct use of GP APIs (or providing optional glue logic for GP) would allow the inner code also to 
```

2023-05-06 05:18 UTC, mhabrat commented on docs/rfcs/accepted/0008-ree_tee_boundary_simplification_and_hardening/README.md
> +leverage GP types and take control over the expected types of parameters that are received, this
```suggestion
leverage GP types and take control over the expected types of parameters that are received. This 
```

2023-05-06 05:18 UTC, mhabrat commented on docs/rfcs/accepted/0008-ree_tee_boundary_simplification_and_hardening/README.md
> +partners' hands have a benefit on the security posture that scale accross integrations.
```suggestion
partners' hands have a benefit on the security posture that scales across integrations.
```

2023-05-10 21:24 UTC, ericeberry commented on docs/rfcs/accepted/0008-ree_tee_boundary_simplification_and_hardening/README.md
> +-
Done

2023-05-10 21:25 UTC, ericeberry commented on docs/rfcs/accepted/0008-ree_tee_boundary_simplification_and_hardening/README.md
> +-
Done

2023-05-10 21:25 UTC, ericeberry commented on docs/rfcs/accepted/0008-ree_tee_boundary_simplification_and_hardening/README.md
> +-
Done

2023-05-10 21:25 UTC, ericeberry approved these changes

2023-05-14 18:32 UTC, mhabrat approved these changes

2023-05-14 18:47 UTC, merged