Issue 72: Implement RFC 0005-integer_overflow_systematic_checks
rdkcentral/tasecureapi pull request #77
Opened 2023-04-21 23:25 UTC by ericeberry

2023-05-22 14:43 UTC, mhabrat requested changes
Have we used a static analyzer like Coverity to confirm all the potential overflow cases have been addressed?

2023-05-22 22:56 UTC, ericeberry commented on reference/src/taimpl/include/porting/overflow.h
> + * This file contains the functions and structures that check the addition operation for overflow.
I looked through the code. There are a few subtract and multiple operations but they all deal with small memory ranges like moving a memory pointer by 16 bytes or small number operations where the calculation would never overflow.

2023-05-22 23:04 UTC, ericeberry commented on reference/src/taimpl/src/internal/cenc.c
> +            return 0;
Used a #define

2023-05-22 23:04 UTC, ericeberry commented on reference/src/taimpl/src/internal/cenc.c
> +            return 0;
Used a #define

2023-05-22 23:05 UTC, ericeberry commented
Is coverity available for Github?

2023-05-23 05:08 UTC, mhabrat commented
> Is coverity available for Github?
This is a question for RDK-M. I doubt it as I don't see any mention of Coverity on the RDK-M wiki. It looks like there may be some support for Cppcheck. If we really wanted to, we could run a standalone Coverity scan of tasecureapi. However, it would be a one-off/manual process.

2023-05-23 20:59 UTC, mhabrat approved these changes

2023-05-23 21:00 UTC, merged