Issue 86: 3.2.1 Code Cleanup
rdkcentral/tasecureapi pull request #89
Opened 2023-07-27 23:20 UTC by ericeberry

2023-08-04 04:16 UTC, mhabrat requested changes

2023-08-04 04:16 UTC, mhabrat commented on reference/src/taimpl/src/porting/svp.c
>              ERROR("unwrap_aes_ecb failed");
unwrap_aes_ecb_internal

2023-08-07 22:46 UTC, ericeberry commented on reference/src/taimpl/src/porting/svp.c
>              ERROR("unwrap_aes_ecb failed");
Done

2023-08-07 23:31 UTC, mhabrat approved these changes

2023-08-08 15:03 UTC, merged