Issue 93: Add soc_key_container version 5
rdkcentral/tasecureapi pull request #94
Opened 2023-08-25 00:15 UTC by ericeberry

2023-08-29 03:46 UTC, mhabrat requested changes

2023-08-29 03:46 UTC, mhabrat commented on reference/src/taimpl/src/porting/otp.c
> +                ERROR("get_root_key failed");
get_common_root_key?

2023-08-29 03:46 UTC, mhabrat commented on reference/src/taimpl/src/ta_sa_key_derive.c
>                  ERROR("otp_common_root_key_ladder failed");
otp_root_key_ladder?

2023-08-29 23:27 UTC, ericeberry commented on reference/src/taimpl/src/porting/otp.c
> +                ERROR("get_root_key failed");
Done

2023-08-29 23:28 UTC, ericeberry commented on reference/src/taimpl/src/ta_sa_key_derive.c
>                  ERROR("otp_common_root_key_ladder failed");
Done

2023-08-31 05:15 UTC, mhabrat approved these changes

2023-08-31 22:16 UTC, merged